### ISSUE TITLE
[X-CLIP] Video demo inference code

### ISSUE THREAD

**Issue by dragen1860** [microsoft/VideoX#57]
Dear author:
    Thanks for publishing your work! it's really insightful!  I want to have a try about the open set video recognition performance. Hence a simple inferece code like this will be much helpful:
![](https://github.com/nbl97/X-CLIP_Model_Zoo/releases/download/v1.0/dunk_.gif)
thanks.

**Comment by nbl97** [comment]
Thanks for your interest and suggestion. For now, you can try open-set recognition by loading the pretrained model and custom configuring your dataset, including the video and candidate categories. Also, we will provide a simple inference code later.

**Comment by fixedwater** [comment]
> Thanks for your interest and suggestion. For now, you can try open-set recognition by loading the pretrained model and custom configuring your dataset, including the video and candidate categories. Also, we will provide a simple inference code later.

Hi, for open set video recognition , should i load the "Zero-shot", "Few-shot" or "Fully supervised" mode ?

**Comment by nbl97** [comment]
> > Thanks for your interest and suggestion. For now, you can try open-set recognition by loading the pretrained model and custom configuring your dataset, including the video and candidate categories. Also, we will provide a simple inference code later.
> 
> Hi, for open set video recognition , should i load the "Zero-shot", "Few-shot" or "Fully supervised" mode ?

Hi, you should load the zero-shot pretrained model.

**Comment by fixedwater** [comment]
> 
thx!, i got a task to label my own dataset with predefined categories (like 800 categories). Is it enough

**Comment by nbl97** [comment]
> > 
> 
> thx!, i got a task to label my own dataset with predefined categories (like 800 categories). Therefore it might be necessary to train on my own dataset for transferring. Is it enough to follow the guide of ![image](https://user-images.githubusercontent.com/53807221/187575626-a9580363-0ae3-46cd-adc2-eb621e5ef245.png) on your readme.md, or anything to change with?

According to my understanding, you can follow the README.md to prepare your dataset and train the model : )

**Comment by fixedwater** [comment]
> > > 
> > 
> > 
> > thx!, i got a task to label my own dataset with predefined categories (like 800 categories). Therefore it might be necessary to train on my own dataset for transferring. Is it enough to follow the guide of ![image](https://user-images.githubusercontent.com/53807221/187575626-a9580363-0ae3-46cd-adc2-eb621e5ef245.png) on your readme.md, or anything to change with?
> 
> According to my understanding, you can follow the README.md to prepare your dataset and train the model : )

perfect! thanks for your amazing project

**Comment by NielsRogge** [comment]
Hi,

I've got something which will make your life a bit easier ;) see the notebook at https://github.com/microsoft/VideoX/issues/61#issue-1360145878

**Comment by dribnet** [comment]
Thanks @NielsRogge - the [colab notebook in that comment](https://colab.research.google.com/drive/1upFMg-FPNP_D8dxeYWTju6lpYldZk8AJ?usp=sharing) is super helpful!

I wanted to check if anyone could verify something about this result from the xclip `processor`.
```python
inputs = processor(text=["playing sports", "eating spaghetti", "go shopping"], videos=list(video), return_tensors="pt", padding=True)

# forward pass
with torch.no_grad():
    outputs = model(**inputs)

probs = outputs.logits_per_video.softmax(dim=1)
```

Presumably all text provided to the model in this way is also going through the trained video-specific prompt generator before being scored against the video?

Just trying to make sure I understand the sematics correctly of these pre-trained models. For example, in this case I would expect models fully-supervised on Kinetics-400 to expect only succinct text labels as text input and longer more descriptive captions would be outside of the training distribution.

**Comment by NielsRogge** [comment]
> Presumably all text provided to the model in this way is also going through the trained video-specific prompt generator before being scored against the video?

Yes, that's correct.

> For example, in this case I would expect models fully-supervised on Kinetics-400 to expect only succinct text labels as text input and longer more descriptive captions would be outside of the training distribution.

Yes, but note that the authors of X-CLIP started from the weights of OpenAI's CLIP model, which has seen 400 million (image, text) pairs. This allows the model to also work on longer text descriptions. It's basically a sort of fine-tuning of CLIP.

**Comment by RaiAmanRai** [comment]
> Hi,
> 
> I've got something which will make your life a bit easier ;) see the notebook at [#61 (comment)](https://github.com/microsoft/VideoX/issues/61#issue-1360145878)

Hi @NielsRogge , thanks for the notebook.
I was trying to play around with it and noticed I cannot pass more than 8 frames to the model

```
def sample_frame_indices(clip_len, frame_sample_rate, seg_len):
    converted_len = int(clip_len * frame_sample_rate)
    end_idx = np.random.randint(converted_len, seg_len)
    start_idx = end_idx - converted_len
    indices = np.linspace(start_idx, end_idx, num=clip_len)
    indices = np.clip(indices, start_idx, end_idx - 1).astype(np.int64)
    return indices

vr = VideoReader(file_path, num_threads=1, ctx=cpu(0))

# sample 16 frames
vr.seek(0)
indices = sample_frame_indices(clip_len=17, frame_sample_rate=1, seg_len=len(vr))
video = vr.get_batch(indices).asnumpy()
print(video.shape)

>>> (17, 360, 640, 3)
```

and pass the numpy arrray to
```
model_name = "microsoft/xclip-base-patch32"
processor = XCLIPProcessor.from_pretrained(model_name)
model = XCLIPModel.from_pretrained(model_name)

inputs = processor(text=["reading code", "writing code", "inspecting code"], videos=list(video), return_tensors="pt", padding=True)

# forward pass
with torch.no_grad():
    outputs = model(**inputs)

probs = outputs.logits_per_video.softmax(dim=1)
probs
```
I get `RuntimeError: shape '[2, 8, 768]' is invalid for input of size 13056`

**Comment by NielsRogge** [comment]
Hi,

It depends on which model you're using. If you use https://huggingface.co/microsoft/xclip-base-patch16-zero-shot, then the number of frames should be 32 (as this model was trained on 32 frames per video as seen [here](https://huggingface.co/microsoft/xclip-base-patch16-zero-shot/blob/main/config.json#L217)).

You can also check this as follows:

```
from transformers import XCLIPModel

model = XCLIPModel.from_pretrained("microsoft/xclip-base-patch32"")
print(model.config.vision_config.num_frames)
```

**Comment by RaiAmanRai** [comment]
Oh..somehow missed that. Thanks for pointing out!

**Comment by Hwijune** [comment]
gpu is not working, is there any other way?

model = XCLIPModel.from_pretrained(model_name).to('cuda:0')

**Comment by opentld** [comment]
> Thanks for your interest and suggestion. For now, you can try open-set recognition by loading the pretrained model and custom configuring your dataset, including the video and candidate categories. Also, we will provide a simple inference code later.

excuse me , is your simple inference code ready? :)

**Comment by Hwijune** [comment]
> What's the error message you're getting?

i got error message -> segmentation fault (core dumped)

This part doesn't work -> model = model.to(device) 

```python
np.random.seed(0)

def sample_frame_indices(clip_len, frame_sample_rate, seg_len):
    converted_len = int(clip_len * frame_sample_rate)
    end_idx = np.random.randint(converted_len, seg_len)
    start_idx = end_idx - converted_len
    indices = np.linspace(start_idx, end_idx, num=clip_len)
    indices = np.clip(indices, start_idx, end_idx - 1).astype(np.int64)
    return indices

vr = VideoReader(file_path, num_threads=1, ctx=cpu(0))

# sample 16 frames
vr.seek(0)
indices = sample_frame_indices(clip_len=8, frame_sample_rate=1, seg_len=len(vr))
video = vr.get_batch(indices).asnumpy()

device = "cuda:0" if torch.cuda.is_available() else "cpu"
print(device)

#model_name = "microsoft/xclip-base-patch32-16-frames"
#model_name = "microsoft/xclip-base-patch32"
#model_name = "microsoft/xclip-base-patch16-kinetics-600"
model_name = "microsoft/xclip-large-patch14-kinetics-600"

model = XCLIPModel.from_pretrained(model_name)
model = model.to(device)
print("model load")

processor = XCLIPProcessor.from_pretrained(model_name)
inputs = processor(text=k600_names, videos=list(video), return_tensors="pt", padding=True)

# forward pass
with torch.no_grad():
    outputs = model(**inputs)

probs = outputs.logits_per_video.softmax(dim=1)
np.set_printoptions(suppress=True)

result = dict(zip(k600_names, probs[0].numpy().tolist()))

res_topk5 = sorted(result.items(), key = lambda item: item[1], reverse = True)[:5]
for i in res_topk5:
    print(i)
```

**Comment by NielsRogge** [comment]
Hi,

PyTorch places your model on the device in-place, no need to do model = model.to(device), just `model.to(device)` is enough.

**Comment by Hwijune** [comment]
> Hi,
> 
> PyTorch places your model on the device in-place, no need to do model = model.to(device), just `model.to(device)` is enough.

Hi. 

i used torch 1.11+cuda 10.2 version

I modified the code, but the same error message comes out.

Is there any other reason?

```
model = XCLIPModel.from_pretrained(model_name)
model.to(device)
print("model load")

processor = XCLIPProcessor.from_pretrained(model_name)
inputs = processor(text=k600_names, videos=list(video), return_tensors="pt", padding=True)

# forward pass
with torch.no_grad():
    outputs = model(**inputs)

probs = outputs.logits_per_video.softmax(dim=1)
```

**Comment by Hwijune** [comment]
> > What's the error message you're getting?
> 
> i got error message -> segmentation fault (core dumped)
> 
> This part doesn't work -> model = model.to(device)
> 
> I want to use gpu.
> 
> It's working fine with the cpu
> 
> ```python
> np.random.seed(0)
> 
> def sample_frame_indices(clip_len, frame_sample_rate, seg_len):
>     converted_len = int(clip_len * frame_sample_rate)
>     end_idx = np.random.randint(converted_len, seg_len)
>     start_idx = end_idx - converted_len
>     indices = np.linspace(start_idx, end_idx, num=clip_len)
>     indices = np.clip(indices, start_idx, end_idx - 1).astype(np.int64)
>     return indices
> 
> vr = VideoReader(file_path, num_threads=1, ctx=cpu(0))
> 
> # sample 16 frames
> vr.seek(0)
> indices = sample_frame_indices(clip_len=8, frame_sample_rate=1, seg_len=len(vr))
> video = vr.get_batch(indices).asnumpy()
> 
> device = "cuda:0" if torch.cuda.is_available() else "cpu"
> print(device)
> 
> #model_name = "microsoft/xclip-base-patch32-16-frames"
> #model_name = "microsoft/xclip-base-patch32"
> #model_name = "microsoft/xclip-base-patch16-kinetics-600"
> model_name = "microsoft/xclip-large-patch14-kinetics-600"
> 
> model = XCLIPModel.from_pretrained(model_name)
> model = model.to(device)
> print("model load")
> 
> processor = XCLIPProcessor.from_pretrained(model_name)
> inputs = processor(text=k600_names, videos=list(video), return_tensors="pt", padding=True)
> 
> # forward pass
> with torch.no_grad():
>     outputs = model(**inputs)
> 
> probs = outputs.logits_per_video.softmax(dim=1)
> np.set_printoptions(suppress=True)
> 
> result = dict(zip(k600_names, probs[0].numpy().tolist()))
> 
> res_topk5 = sorted(result.items(), key = lambda item: item[1], reverse = True)[:5]
> for i in res_topk5:
>     print(i)
> ```

@NielsRogge thank you

i just downgrade my torch version 1.11.0 -> 1.8.0

working fine in gpu :)

**Comment by zyhzyh88** [comment]
Dear author:
Thanks for your promising work. We have followed your code conducted on zero-shot of UCF-101, the test set has only one category, however, as training progresses, the test performance gradually decreases from the 1st epoch (The attached is our training log). We want you to seek help. Thank you! 
[log_rank0.txt](https://github.com/microsoft/VideoX/files/9986310/log_rank0.txt)
