### ISSUE TITLE
DataSet Preparation and Use of  Decord

### ISSUE THREAD

**Issue by aliman80** [microsoft/VideoX#59]
Hi, Thank you for your wonderful work. i was trying to download all the requirements to reproduce the results. I have following trivial  queries please;

1:  Where and how can we use decord in this code base.
2: If possible can you elaborate the arrangment of dataset. what i understood for the option 2 is that we need to download zipped data.
3: Where in zipped files are we using train, test label files.

**Comment by nbl97** [comment]
Thanks for your interest in our work~Here are my responses:
1. We borrow the pipeline of loading video from MMAction2. Specifically, we define the pipeline in [datasets/build.py#L248](https://github.com/microsoft/VideoX/blob/master/X-CLIP/datasets/build.py#L248). All the `class` about data preparation and augmentation are defined in [datasets/pipeline.py](https://github.com/microsoft/VideoX/blob/master/X-CLIP/datasets/pipeline.py), where you can find [DecordInit](https://github.com/microsoft/VideoX/blob/master/X-CLIP/datasets/pipeline.py#L1766) and [DecordDecode](https://github.com/microsoft/VideoX/blob/master/X-CLIP/datasets/pipeline.py#L1818).
2. You do not need to download zipped data. The provided two options are just about how to organize the dataset, not about how to download the dataset. You can download the dataset by a means convenient to you. After the downloading, there are two options to organize them: putting all the videos (including training set and testing set) together in a FOLDER (option 1) or TAR FILE (option 2).
3. Same with option 1, we still need `train.txt` and `val.txt` to list the videos and labels. We have updated the README for easy understanding.

**Comment by aliman80** [comment]
Thank you for your kind response.
