### ISSUE TITLE
[X-CLIP] Question about Table 3

### ISSUE THREAD

**Issue by jinyf123** [microsoft/VideoX#63]
Hi, thanks for your great paper.  
In Table 3 of this paper, the zero-shot performance of ActionCLIP is 40.8% and 58.3%, but according to Figure 3 of the [ActionCLIP](https://arxiv.org/pdf/2109.08472.pdf), the zero-shot performance of these two datasets is about 50% and 70%.  
Is there any difference in implementation?

**Comment by nbl97** [comment]
Hi, thanks for your interest in our work.
In Table 3, “ActionCLIP” here refers to "ActionCLIP-MeanP" which we re-implemented with the official codes.

**Comment by jinyf123** [comment]
ok, thanks
