### ISSUE TITLE
Doesn't the language model need to update parameters during training? 

### ISSUE THREAD

**Issue by zhangfudiyi** [microsoft/VideoX#65]
Doesn't the language model need to update parameters during training? 
![01366e73850e4101b13ef2feaf51834c](https://user-images.githubusercontent.com/18095991/188805439-e4bad7a5-e3f3-4a86-bab2-2f9dfda1d761.png)

**Comment by nbl97** [comment]
Thanks for your interest in our work~ 
The text encoder does not need to be updated : )

**Comment by nbl97** [comment]
I'm closing this issue, but pls feel free to ping me if there are further questions.
