### ISSUE TITLE
setup without gpu

### ISSUE THREAD

**Issue by nattikahana** [microsoft/VideoX#67]
Hi my computer doesn't have a GPU and the command 
"pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./"
doesn't work for me I would like to know if there is a way to run the setup on my CPU,
thanks

**Comment by nbl97** [comment]
It is almost impossible to train such models without GPUs, so I guess you just want to do inference. Then, you do not have to install apex, but you still need to manually remove some GPU-related parts of the code, such as `.cuda()`. We are sorry for this. But the good news is that our code has been integrated into [Hugging Face](https://huggingface.co/models?other=xclip), maybe it is more convenient for you to use our model by that.

**Comment by nbl97** [comment]
I'm closing this issue, but pls feel free to ping me if there are further questions.
