### ISSUE TITLE
Configs for reproducing results for few-shot experiments of X-CLIP

### ISSUE THREAD

**Issue by muzairkhattak** [microsoft/VideoX#70]
Dear authors,

Thank you for your incredible work and a great repository. 

I wanted to ask if you could provide instructions on how to train X-CLIP on UCF101 and HMDB in few-shot settings? I am able to see the provided few-shot trained weights and log files but I could not find any instructions/config-files to re-train from scratch the few-shot experiments.

Your kind support will be really helpful.

Thank you.

**Comment by nbl97** [comment]
Thanks for your interest~
There is nothing special for few-shot experiments. All the hyperparameters are the same as fully-supervised experiments. You can organize the data according to the README and run the experiments with the same commands as Kinetics. The config files are in the `conifgs` folder, [hmdb](https://github.com/microsoft/VideoX/blob/master/X-CLIP/configs/hmdb51/16_32.yaml) and [ucf](https://github.com/microsoft/VideoX/blob/master/X-CLIP/configs/ucf101/16_32.yaml).
Hope this can help you.

**Comment by muzairkhattak** [comment]
Thank you for your immediate response. I will follow the instructions accordingly.
