### ISSUE TITLE
The process of reference  (X-CLIP)

### ISSUE THREAD

**Issue by Xiyu-AI** [microsoft/VideoX#72]
Hello, it is a very meaningful work. I would like to ask, in the reference stage, the input is video, what is the corresponding input text???  Or do you just input the video and automatically output text???

**Comment by nbl97** [comment]
Thanks for your interest~
The input text is category names. Hope this can help you

**Comment by nbl97** [comment]
I'm closing this issue. Pls feel free to ping me if there are further questions.
