### ISSUE TITLE
[XCLIP] access raw model on huggingface

### ISSUE THREAD

**Issue by wren93** [microsoft/VideoX#78]
Hi, 
Thank you very much for sharing this great work. I had a question regarding the huggingface implementation for XCLIP: is there a way to access the raw model (with CLIP pretrained weights loaded but without loading other weights from a finetuned checkpoint) on HF? Seems that all the models released in the model zoo are either finetuned fully supervised on K400/K600 or in a few shot fashion on UCF/HMDB. Thanks in advance.

**Comment by nbl97** [comment]
Thanks for your interest.
I know your point, but we do not provide such a model on HF because it seems to be of little use. If necessary, maybe you can re-load the CLIP weights and re-initialize the other parts. Sorry for the inconvenience.
