### ISSUE TITLE
About Frame Sampling

### ISSUE THREAD

**Issue by yusufani** [microsoft/VideoX#84]
Hi,

Thank you for X-Clip project. 
While running[ the code](https://colab.research.google.com/drive/1upFMg-FPNP_D8dxeYWTju6lpYldZk8AJ?usp=sharing) in Huggingface to try it out, I noticed that 8 frames are sampled sequentially. Do these frames have to be sequential or would it make sense to randomly get 8 frames in 1 second?

![image](https://user-images.githubusercontent.com/35346311/216312165-6aaf0329-d736-4153-8b51-26deaeebd319.png)

**Comment by nbl97** [comment]
Thanks for your interest. In the original paper, the frames are sampled using a sparse strategy, i.e., the frames are uniformly sampled to capture the global information.  In your code snippet, you can control the interval by frame_sample_rate. Hope this can help you.

**Comment by yusufani** [comment]
Thank you for your answer. I tried with a frame for each second and it works quite well 🥳

**Comment by nbl97** [comment]
Pls feel free to ping me if there are further questions.
