### ISSUE TITLE
confusion of **drop path** 

### ISSUE THREAD

**Issue by ignitemylife** [microsoft/VideoX#85]
https://github.com/microsoft/VideoX/blob/master/X-CLIP/models/cct.py#L52

we see drop path usually at BatchSize dimension, but in this repo.， I find it is applied at **token length** dimension, is there some mistakes or misconception here?

**Comment by nbl97** [comment]
It is a mistake, and we will fix that later in case of misleading.
Thanks for your interest and reminder.

**Comment by ignitemylife** [comment]
> 

thank you for your reply! Best wishes
