### ISSUE TITLE
What is the relation with your X-CLIP and X-CLIP by Yiwei Ma et. al?

### ISSUE THREAD

**Issue by tetsu-kikuchi** [microsoft/VideoX#92]
I noticed there is another model called X-CLIP by Yiwei Ma et. al, [arXiv:2207.07285](https://arxiv.org/abs/2207.07285).

Their paper was submitted on arXiv on July 2022, while your paper (Bolin Ni et. al, [2208.02816](https://arxiv.org/abs/2208.02816)) on August 2022, one month later. 
At least, it seems that the priority of the name (X-CLIP) should be given to Yiwei Ma.  But you used the same name, and even more, you did not cite their paper (Yiwei Ma et. al) in your paper (Bolin Ni et. al).  It is hardly possible that you did not know the existence of their paper.  

Could you explain the situation?

**Comment by nbl97** [comment]
Thank you for your interest.  To clarify, our work manuscript was submitted to the ECCV 2022 conference on March 8, 2022, which predates the publication of the paper you have mentioned, and finally our work was accepted by ECCV 2022. Therefore, it was not possible for us to have knowledge of that particular work at the time of our submission. The submission log on the CMT system will substantiate this. 

Additionally, while recognizing the excellence of the work by Yiwei Ma et al., it is crucial to highlight that the core focus of our research diverges notably from theirs. Our efforts have been primarily directed towards the domain of video recognition, whereas the paper by Yiwei Ma et al. emphasizes on video retrieval. As such, the foundational methodologies and motivations that underpin both papers are markedly distinct.

We will certainly consider including more comprehensive citations in our future work.  Should you have any additional queries or require further clarification, please reach out to me via email.
