### ISSUE TITLE
About training logs in SeqTrack.

### ISSUE THREAD

**Issue by RelayZ** [microsoft/VideoX#94]
Hello! This is an excellent work. I don't see the training log provided in the model zoo. Can you provide the training log of the reproduced results later? like STARK.

**Comment by JinxiaXie** [comment]
Yes, I think I need a training log too. When I run the this code seting the batch size to 2 (Since my computation power is limitted, I just want to try to run the code), the IOU decreases step by step from  0.05+. Can somebody Know why? Thank you so much.

**Comment by chenxin-dlut** [comment]
Thank you, the logs have been updated, pls see MODEL_ZOO.md
