### ISSUE TITLE
Sampling strategy in X-CLIP

### ISSUE THREAD

**Issue by MohamedAfham** [microsoft/VideoX#99]
Hi,

Thanks for the amazing work. I have noticed in Table. 11 of the paper that you have done a comparison on sampling methods for X-CLIP (Dense and Sparse sampling). Is there a config in the code which we can play around to change the sampling from sparse to dense. I'm assuming the default sampling in the code is sparse sampling.

Thanks.

**Comment by nbl97** [comment]
Thanks for your interest. Yes, the default sampling strategy is sparse sampling. You can change the strategy by modifying [this line](https://github.com/microsoft/VideoX/blob/master/X-CLIP/datasets/build.py#L249) for training and [this line](https://github.com/microsoft/VideoX/blob/master/X-CLIP/datasets/build.py#L287) for evaluation. For example, `dict(type='SampleFrames', clip_len=config.data.num_segments, frame_interval=64//config.data.num_segments, num_clips=1)`  means sampling `config.data.num_segments` frames densely. The data pipeline is borrowed from [mmaction2](https://github.com/open-mmlab/mmaction2) where you can learn more about the configuration detail.
